---
title: "Nominal House Prices in Luxembourg - Analyses"
author: "Eddie Hearn"
date: "`r Sys.Date()`"
---

```{r , warning = FALSE , message = FALSE}

library(dplyr)
library(ggplot2)
library(janitor)
library(purrr)
library(tidyr)

home_dir = "C:/Users/ehearn/OneDrive - Secretariat Advisors LLC/Desktop/Miscellaneous/housing/datasets"

```

Load datasets:

```{r}

commune_level_data = read.csv(paste0(home_dir , "/house_prices_commune_level_data.csv"))

country_level_data = 
  read.csv(paste0(home_dir , "/house_prices_country_level_data.csv"))

```


Compute Laspeyeres for commune-level data.

```{r}

commune_level_data = get_laspeyeres(commune_level_data)

```

Also compute index for whole country.

```{r}

country_level_data = get_laspeyeres(country_level_data)

```

Create plots for 5 communes and compare the price evolution in the communes to the national price evolution. First, list the communes:

```{r}

communes = c("Luxembourg",
              "Esch-sur-Alzette",
              "Mamer",
              "Schengen",
              "Wincrange")

```


Create commune plots.

```{r , results = "asis"}

res = lapply(communes , function(x){
  print(make_plot(x))
}
)



```







